name = "test"
main = "src/index.ts"
compatibility_date = "2025-09-06"

[[durable_objects.bindings]]
name = "ReversiDO"
class_name = "ReversiDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ReversiDO"]
