name = "test"
main = "index.ts"
compatibility_date = "2024-09-06"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ReversiDO"]

[durable_objects]
bindings = [
  { name = "ReversiDO", class_name = "ReversiDO" }
]

[assets]
binding = "ASSETS"
directory = "./public"
